Repository SOPT-31th-App2-Kyobo-Electronic-Libary/Kyobo-AOS, pull requests merged in 2022-11, with the labels that each got.

#9 #7 [ui] 홈 화면 뷰 구성
  .idea/gradle.xml
  app/src/main/java/com/junewon/kyobo_android/presentation/MainActivity.kt
  app/src/main/res/drawable/ic_home_dropdown.xml
  app/src/main/res/drawable/ic_home_favorite_off.xml
  app/src/main/res/drawable/ic_home_favorite_on.xml
  app/src/main/res/drawable/ic_home_search.xml
  app/src/main/res/drawable/img_dummy_book.png
  app/src/main/res/drawable/selector_home_btn_favorite.xml
  app/src/main/res/drawable/shape_home_btn_apply.xml
  app/src/main/res/drawable/shape_home_btn_return.xml
  app/src/main/res/drawable/shape_home_card_best.xml
  app/src/main/res/drawable/shape_home_tag_days.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_best.xml
  app/src/main/res/layout/item_home_book.xml
  app/src/main/res/layout/item_home_borrowed.xml
  app/src/main/res/values/styles.xml
Labels: ui, 수민 :cat:

#15 #11 [feat] Search뷰 UI
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/junewon/kyobo_android/data/entity/RecentBook.kt
  app/src/main/java/com/junewon/kyobo_android/presentation/search/Empty.kt
  app/src/main/java/com/junewon/kyobo_android/presentation/search/SearchActivity.kt
  app/src/main/java/com/junewon/kyobo_android/presentation/search/SearchScreen.kt
  app/src/main/java/com/junewon/kyobo_android/util/DpToSp.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/BasicButton.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/KyoboButtons.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/RecentBookItem.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/RecentBooks.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/RecentSearchTerm.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/SearchAppBar.kt
  app/src/main/java/com/junewon/kyobo_android/util/componet/SearchTextField.kt
  app/src/main/java/com/junewon/kyobo_android/util/theme/Shape.kt
  app/src/main/java/com/junewon/kyobo_android/util/theme/Theme.kt
  app/src/main/java/com/junewon/kyobo_android/util/theme/Typhograph.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_kyobo_launcher.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_delete.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_kyobo_launcher.png
  app/src/main/res/mipmap-hdpi/ic_kyobo_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_kyobo_launcher.png
  app/src/main/res/mipmap-mdpi/ic_kyobo_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_kyobo_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_kyobo_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_kyobo_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_kyobo_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_kyobo_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_kyobo_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/Deps.kt
  buildSrc/src/main/java/Versions.kt
Labels: ui, pull request :fire:, 준원 :bear:

#22 [ui, feat] 메인 페이지 뷰 수정, 검색화면 이동 로직 구현
  README.md
  app/src/main/java/com/junewon/kyobo_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/junewon/kyobo_android/presentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_best.xml
  app/src/main/res/layout/item_home_borrowed.xml
  app/src/main/res/layout/item_home_catagory.xml
  app/src/main/res/layout/item_home_new.xml
Labels: feat, ui, pull request :fire:, 수민 :cat:
